github: high-cde
custom: 
  - "https://x-zdos.it/sponsor"
  - "https://ko-fi.com/zdos"
  - "https://cloudx.zdos.dev/support"
message: >
  Supporta lo sviluppo di xCLOUD Enterprise e contribuisci alla crescita dell’ecosistema CloudX × ZDOS.
  Il progetto evolve il Developer Hub in una piattaforma moderna, modulare e orientata alle imprese.
  Sponsorizzando aiuti l’espansione dei moduli Nexus, Terminal, Portal, DSN Layer e delle integrazioni enterprise.
